#!/bin/bash
# Quick Deploy Script - Deploy to Vercel + Render in minutes!

echo "🚀 Starting deployment..."
echo ""

# Step 1: Git Commit
echo "📝 Step 1: Committing to GitHub..."
cd /workspaces/Platforms-token-forge-ai-software-
git add .
git commit -m "🚀 Deploy Web3 Solana Token Forge dapp to production" || echo "Nothing to commit"
git push

echo "✅ Pushed to GitHub"
echo ""

# Step 2: Instructions
echo "================================"
echo "🎯 DEPLOYMENT INSTRUCTIONS"
echo "================================"
echo ""
echo "✅ GitHub: Complete ✓"
echo ""
echo "📊 Next Steps (Do these in your browser):"
echo ""
echo "1️⃣  DEPLOY FRONTEND TO VERCEL:"
echo "   👉 Visit: https://vercel.com/new"
echo "   - Click 'Import Git Repository'"
echo "   - Select your GitHub repo"
echo "   - Root Directory: frontend"
echo "   - Click 'Deploy'"
echo "   ⏱️  Wait 2-3 minutes"
echo "   ✅ You'll get: https://your-app.vercel.app"
echo ""
echo "2️⃣  DEPLOY BACKEND TO RENDER:"
echo "   👉 Visit: https://render.com"
echo "   - Sign up (free)"
echo "   - New Web Service"
echo "   - Select GitHub repo"
echo "   - Root Directory: backend"
echo "   - Start Command: npm start"
echo "   - Click 'Create Web Service'"
echo "   ⏱️  Wait 5 minutes"
echo "   ✅ You'll get: https://your-backend.onrender.com"
echo ""
echo "3️⃣  CONNECT THEM:"
echo "   - In Vercel, go to Settings → Environment Variables"
echo "   - Add: REACT_APP_BACKEND_URL = https://your-backend.onrender.com"
echo "   - Redeploy in Vercel"
echo ""
echo "4️⃣  TEST YOUR DAPP:"
echo "   👉 Open: https://your-app.vercel.app"
echo "   - Install Phantom wallet"
echo "   - Create a token"
echo "   - Success! 🎉"
echo ""
echo "================================"
echo "📊 COSTS"
echo "================================"
echo "✅ Everything: FREE FOREVER"
echo "✅ No credit card needed"
echo "✅ Unlimited deployments"
echo ""
echo "================================"
echo "⏱️  TIMELINE"
echo "================================"
echo "Step 1 (GitHub): 1 minute ✓"
echo "Step 2 (Vercel): 2-3 minutes"
echo "Step 3 (Render): 5 minutes"
echo "Step 4 (Connect): 1 minute"
echo "Step 5 (Test): 2 minutes"
echo ""
echo "Total: ~10 minutes to live! 🚀"
echo ""
echo "================================"
echo "🎊 All set! Now go to Vercel.com"
echo "================================"
